### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by james-grant1** [JDBetteridge/nbfancy#12] opened 2019-01-18 13:23 UTC
Example and tutorial (which should test all functionalilty) successful builds as integration tests.
More unit tests for specific functionality?

**Comment by JDBetteridge** [comment] 2019-01-20 21:42
Marking as duplicate of:
[Issue 6](https://github.com/JDBetteridge/nbfancy/issues/6)
Create new issue if need for additional unit tests arises.

**Closed as completed by JDBetteridge** 2019-01-20 21:42 UTC
Labels: duplicate
